# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - team: csa-cto-repo-admins
    role: Maintain
  - team: CSA_CTO_REPO_CONTRIBUTORS
    role: Push
  - team: natalieturnerdir
    role: Push
  - team: DanOsbornDirects
    role: Push
  - team: csactoengineering
    role: Push
